name: tmdb_proxy
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  encrypt: ^5.0.3
  envied: ^0.5.4+1
  http: ^1.2.2
  pointycastle: ^3.9.1
  shelf_cors_headers: ^0.1.5
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
